### ISSUE TITLE
Cannot find module 'express'

### ISSUE THREAD

**Issue by hashir-asghar** [Sobhan-SRZA/All-For-One-Bot#11]
Uncaught Error Error: Cannot find module 'express'
Require stack:
- e:\nuker\multipurpose\All-For-One-Bot-1.0.0\All-For-One-Bot-1.0.0\index.js
    at Module._resolveFilename (internal/modules/cjs/loader:1075:15)
    at Module._load (internal/modules/cjs/loader:920:27)
    at Module.require (internal/modules/cjs/loader:1141:19)
    at require (internal/modules/cjs/helpers:110:18)
    at <anonymous> (e:\nuker\multipurpose\All-For-One-Bot-1.0.0\All-For-One-Bot-1.0.0\index.js:3:17)
    at Module._compile (internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (internal/modules/cjs/loader:1308:10)
    at Module.load (internal/modules/cjs/loader:1117:32)
    at Module._load (internal/modules/cjs/loader:958:12)
    at executeUserEntryPoint (internal/modules/run_main:81:12)
    at <anonymous> (internal/main/run_main_module:23:47)

sir i tried install.bat and update.bat then i tried npm install express but getting this error

**Comment by Sobhan-SRZA** [comment]
Hello
OK
I will create a video for you 😉

**Comment by Sobhan-SRZA** [comment]
> Uncaught Error Error: Cannot find module 'express' Require stack:
> 
> * e:\nuker\multipurpose\All-For-One-Bot-1.0.0\All-For-One-Bot-1.0.0\index.js
>   at Module._resolveFilename (internal/modules/cjs/loader:1075:15)
>   at Module._load (internal/modules/cjs/loader:920:27)
>   at Module.require (internal/modules/cjs/loader:1141:19)
>   at require (internal/modules/cjs/helpers:110:18)
>   at  (e:\nuker\multipurpose\All-For-One-Bot-1.0.0\All-For-One-Bot-1.0.0\index.js:3:17)
>   at Module._compile (internal/modules/cjs/loader:1254:14)
>   at Module._extensions..js (internal/modules/cjs/loader:1308:10)
>   at Module.load (internal/modules/cjs/loader:1117:32)
>   at Module._load (internal/modules/cjs/loader:958:12)
>   at executeUserEntryPoint (internal/modules/run_main:81:12)
>   at  (internal/main/run_main_module:23:47)
> 
> sir i tried install.bat and update.bat then i tried npm install express but getting this error

https://user-images.githubusercontent.com/90289153/259035012-24ca2e3d-845d-4e4e-8b17-b6e8485b9459.mp4
setup bot like this video

**Comment by BestGamersH** [comment]
It still has the same issue

**Comment by Sobhan-SRZA** [comment]
Did you reinstall the source?
If you get the same issue again, call me at discord. (mr.sinre#0)
